{% set name = "radical.gtod" %}
{% set version = "1.16.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1fe9da598a965c7194ed9c7df49d5b30632a11a7f9ece12152bea9aaa91bd4b8

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py2k or py>39 or win]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python
    - radical.utils

test:
  imports:
    - radical.gtod

about:
  home: https://github.com/radical-cybertools/radical.gtod
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE.md
  summary: Current time in seconds since epoch
  description: |
    This Python package provides a single method, gtod, which returns the 
    current time in seconds since epoch (01.01.1970) with sub-second resolution.
  dev_url: https://github.com/radical-cybertools/radical.gtod

extra:
  recipe-maintainers:
    - andre-merzky
    - mtitov
