{% set name = "radical.gtod" %}
{% set version = "1.61.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/radical_gtod-{{ version }}.tar.gz
  sha256: e08037c142130130937d92b140a5a4f192146b97992488ab50e325090f8dd719

build:
  skip: true  # [py<37 or win]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - cross-python_{{ target_platform }}    # [build_platform != target_platform]
    - python                                # [build_platform != target_platform]
  host:
    - python
    - setuptools
    - pip
  run:
    - python
    - radical.utils >=1.60

test:
  imports:
    - radical.gtod

about:
  home: https://github.com/radical-cybertools/radical.gtod
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE.md
  summary: Current time in seconds since epoch
  description: |
    This Python package provides a single method, gtod, which returns the
    current time in seconds since epoch (01.01.1970) with sub-second resolution.
  dev_url: https://github.com/radical-cybertools/radical.gtod

extra:
  recipe-maintainers:
    - andre-merzky
    - mtitov
    - xylar
